### ISSUE TITLE
Place new emoji at current cursor position

### ISSUE THREAD

**Issue by zilions** [LevchenkoD/twemoji-input#1]
First of all, great job with the plugin!

Currently, each new emoji is always placed at the end of the textarea text. It would be great to have it placed at the current cursor position incase the user decides to go back to the start of their entered text to add in a new emoji.

This is obviously more of an enhancement than an issue.

**Comment by vladbondarenko97** [comment]
This would be an awesome enhancement. Any updates? It's been 2 years since last commit.

**Comment by levchenkod** [comment]
Hey guys, thanks!

Checkout latest commit, emoji placement and some other stuff has been fixed. It's better later than never.
